name: authenticator_extended
description: Authenticator Extended

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  barcode_scan: "^3.0.1"
  otp: ^2.2.1
  dart_otp: ^1.3.0
  countdown: any
  shared_preferences: ^0.5.8
  rxdart: ^0.24.1
  cuberto_bottom_bar:

dev_dependencies:
#  flutter_test:
#    sdk: flutter


flutter:
  uses-material-design: true
